mybatis-plus:
  global-config:
    banner: off
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring_db?useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    banner-mode: off
server:
  port: 80
