---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by cjc20.
--- DateTime: 11/11/2022 11:46 am
---
---
if KEYS[1] == "key1" then
    redis.call('set', KEYS[1], ARGV[1])
    redis.call('set', KEYS[2], ARGV[2])
end