---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jon.
--- DateTime: 4/11/2022 4:08 pm
---

-- 验证线程标志位
if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
end
return 0